# Generated by Django 5.1.7 on 2025-04-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('acessorio', models.ManyToManyField(blank=True, to='garagem.acessorio')),
                ('cor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='garagem.cor')),
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='garagem.modelo')),
            ],
        ),
    ]
